// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum eFB_Type : int
{
 Base = 0,
 fping = 1,
 fplayer = 2,
 fid = 3,
 fout = 4,
 fmob = 5,
 fboom = 6,
};

