// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct fmob : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static fmob GetRootAsfmob(ByteBuffer _bb) { return GetRootAsfmob(_bb, new fmob()); }
  public static fmob GetRootAsfmob(ByteBuffer _bb, fmob obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public fmob __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public eFB_Type FType { get { int o = __p.__offset(4); return o != 0 ? (eFB_Type)__p.bb.GetInt(o + __p.bb_pos) : eFB_Type.Base; } }
  public int Id { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Hp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float X { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<fmob> Createfmob(FlatBufferBuilder builder,
      eFB_Type fType = eFB_Type.Base,
      int id = 0,
      int hp = 0,
      float x = 0.0f,
      float y = 0.0f) {
    builder.StartObject(5);
    fmob.AddY(builder, y);
    fmob.AddX(builder, x);
    fmob.AddHp(builder, hp);
    fmob.AddId(builder, id);
    fmob.AddFType(builder, fType);
    return fmob.Endfmob(builder);
  }

  public static void Startfmob(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddFType(FlatBufferBuilder builder, eFB_Type fType) { builder.AddInt(0, (int)fType, 0); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(1, id, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(2, hp, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(3, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(4, y, 0.0f); }
  public static Offset<fmob> Endfmob(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<fmob>(o);
  }
};

