// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct fping : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static fping GetRootAsfping(ByteBuffer _bb) { return GetRootAsfping(_bb, new fping()); }
  public static fping GetRootAsfping(ByteBuffer _bb, fping obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public fping __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public eFB_Type FType { get { int o = __p.__offset(4); return o != 0 ? (eFB_Type)__p.bb.GetInt(o + __p.bb_pos) : eFB_Type.Base; } }
  public long Time { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<fping> Createfping(FlatBufferBuilder builder,
      eFB_Type fType = eFB_Type.Base,
      long time = 0) {
    builder.StartObject(2);
    fping.AddTime(builder, time);
    fping.AddFType(builder, fType);
    return fping.Endfping(builder);
  }

  public static void Startfping(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddFType(FlatBufferBuilder builder, eFB_Type fType) { builder.AddInt(0, (int)fType, 0); }
  public static void AddTime(FlatBufferBuilder builder, long time) { builder.AddLong(1, time, 0); }
  public static Offset<fping> Endfping(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<fping>(o);
  }
};

